<internal_error>
<sub_system>ERR</sub_system>
<callstack>
	0x7f90862e3171: ccl_err + 0x8171 (_ZN15ERR_STACKWALKER15get_stack_traceEPPKviiPv + 0xb1)
	0x7f90862e5ff5: ccl_err + 0xaff5 (_Z14err_terminatorv + 0x4b)
	0x7f907dcba796: stdc++.so.6 + 0x63796 (_ZN10__cxxabiv111__terminateEPFvvE + 0x6)
	0x7f907dcba7c3: stdc++.so.6 + 0x637c3
	0x7f907dcbaa36: stdc++.so.6 + 0x63a36 (__cxa_rethrow + 0x46)
	0x7f90bca4ab64: QtCore.so.4 + 0x1a5b64 (_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 0x2f4)
	0x7f90bca4f7c4: QtCore.so.4 + 0x1aa7c4 (_ZN16QCoreApplication4execEv + 0xb4)
	   0x401dd8: quartus + 0x1dd8 (_Z8qgq_mainiPPKc + 0x68)
	0x7f9088b43360: ccl_msg + 0x40360 (_Z15msg_main_threadPv + 0x10)
	0x7f9085ea702c: ccl_thr + 0x602c (thr_final_wrapper + 0xc)
	0x7f9088b4341c: ccl_msg + 0x4041c (_Z18msg_thread_wrapperPFPvS_ES_ + 0x62)
	0x7f9086517359: ccl_mem + 0xb359 (_Z18mem_thread_wrapperPFPvS_ES_ + 0x99)
	0x7f90862e3f98: ccl_err + 0x8f98 (_Z18err_thread_wrapperPFPvS_ES_ + 0x27)
	0x7f9085ea73f2: ccl_thr + 0x63f2 (thr_thread_wrapper + 0x15)
	0x7f9088b45622: ccl_msg + 0x42622 (_Z12msg_exe_mainiPPKcPFiiS1_E + 0xa3)
	   0x401eaa: quartus + 0x1eaa (main + 0x26)
	0x7f907d180840: c.so.6 + 0x20840 (__libc_start_main + 0xf0)
	   0x401c89: quartus + 0x1c89
</callstack>
<error>*** Fatal Error: Unhandled Exception</error>
<date>Fri Feb 19 02:21:10 2021
</date>
<version>Version 16.0.0 Build 211 04/27/2016 SJ Standard Edition</version>
</internal_error>